language: node_js
node_js:
  - "6.9.1"
services:
  - mongodb
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
after_script:
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
